server:
  port: 8089 #服务端口
spring:
  application:
    name: warehouse-service-dubbo #微服务id
  cloud:
    nacos: #nacos注册地址
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
dubbo: #dubbo与nacos的通信配置
  application:
    name: warehouse-dubbo #provider在Nacos中的应用id
  registry: #Provider与Nacos通信地址，与spring.cloud.nacos地址一致
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo #通信协议名
    port: 20880 #配置通信端口，默认为20880
  scan:
    base-packages: com.sdjictec.scalidemo.warehouse.dubbo

